devicemap = {
    'a700': 'Acer Iconia A700',
    'ace': 'HTC Desire HD',
    'bravo': 'HTC Desire',
    'crespo': 'Google Nexus S',
    'deb': 'Google Nexus 7 2013 (4G)',
    'dlx': 'HTC Droid DNA',
    'find5': 'Oppo Find 5',
    'flo': 'Google Nexus 7 2013 (Wi-Fi)',
    'galaxysmtd': 'Samsung Galaxy S',
    'grouper': 'Google Nexus 7 2012 (Wi-Fi)',
    'hammerhead': 'Google Nexus 5',
    'hltecan': 'Samsung Galaxy Note 3 (Canada)',
    'hltespr': 'Samsung Galaxy Note 3 (Sprint)',
    'hltetmo': 'Samsung Galaxy Note 3 (T-Mobile)',
    'hltevzw': 'Samsung Galaxy Note 3 (Verizon)',
    'hltexx': 'Samsung Galaxy Note 3 (Global)',
    'honami': 'Sony Xperia Z1 (Google Play Edition)',
    'jflte': 'Samsung Galaxy S4',
    'jflteatt': 'Samsung Galaxy S4 (AT&T)',
    'jfltecan': 'Samsung Galaxy S4 (Canada)',
    'jfltecri': 'Samsung Galaxy S4 (Cricket)',
    'jfltecsp': 'Samsung Galaxy S4 (C Spire)',
    'jfltespr': 'Samsung Galaxy S4 (Sprint)',
    'jfltetmo': 'Samsung Galaxy S4 (T-Mobile)',
    'jflteusc': 'Samsung Galaxy S4 (US Cellular)',
    'jfltevzw': 'Samsung Galaxy S4 (Verizon)',
    'jfltexx': 'Samsung Galaxy S4 (Global)',
    'm7att': 'HTC One (AT&T)',
    'm7spr': 'HTC One (Sprint)',
    'm7tmo': 'HTC One (T-Mobile)',
    'm7ul': 'HTC One (GSM)',
    'm7vzw': 'HTC One (Verizon)',
    'maguro': 'Samsung Galaxy Nexus',
    'maserati': 'Motorola Droid 4',
    'mako': 'Google Nexus 4',
    'n1': 'Oppo N1',
    'n7100': 'Samsung Galaxy Note II',
    'p3110': 'Samsung Galaxy Tab 2 7.0 (Wi-Fi)',
    'spyder': 'Motorola Droid Razr',
    't0lte': 'Samsung Galaxy Note II (GSM LTE)',
    'tilapia': 'Google Nexus 7 2012 (GSM)',
    'togari': 'Sony Xperia Z Ultra',
    'togari_gpe': 'Sony Xperia Z Ultra (Google Play Edition)',
    'toroplus': 'Google Galaxy Nexus (Sprint)',
    'xt1032': 'Motorola Moto G (Global)',
    'xt1053': 'Motorola Moto X (T-Mobile)',
    'xt1060': 'Motorola Moto X (Verizon)'
}
